---
title: "Chapter 8"
author: "Jai Jeffryes"
date: "11/2/2019"
output: html_document
---

8.1. Visualize the residuals. The scatterplots shown below each have a superimposed regression line. If we were to construct a residual plot (residuals versus x) for each, describe what those plots would look like.

a. Random residuals and constant variance.

b. Fan shaped. More widely dispersed residuals at the lower end. The upper end has more positive residuals. This data is problematic for fitting to a regression line. 

8.2. Trends in the residuals. Shown below are two plots of residuals remaining after fitting a linear model to two different sets of data. Describe important features and determine if a linear model would be appropriate for these data. Explain your reasoning.

a. The residuals are fan shaped, so the the variance is dependent on the x value, not good for linear modeling.

b. I think there is a pattern in the residuals, so the sampling is not independant, not good for linear modeling.

8.3. Identify relationships, Part I. For each of the six plots, identify the strength of the relationship (e.g. weak, moderate, or strong) in the data and whether fitting a linear model would be reasonable.

a. Strong and non-linear, concave up.

b. Strong and linear in the positive direction.

c. A weak, positive, linear relationship

d. A weak non-linear relationship, concave down.

e. A strong, negative, linear relationship.

f. A weak association. A linear fit would be reasonable.

8.4 Identify relationships, Part II. For each of the six plots, identify the strength of the relationship (e.g. weak, moderate, or strong) in the data and whether fitting a linear model would be reasonable.

a. Strong, but not linear.

b. Strong, but not linear.

c. Moderate, positive. Linear fit would be reasonable.

d. Weak relationship. Linear fit would be reasonable.

e. Weak relationship. Negative linear fit would be reasonable.

f. Moderate to weak negative linear association.

8.5 Exams and grades. The two scatterplots below show the relationship between final and mid-semester exam grades recorded during several years for a Statistics course at a university.
(a) Based on these graphs, which of the two exams has the stronger correlation with the final exam grade? Explain.

Exam 2. The residuals have less variance.

(b) Can you think of a reason why the correlation between the exam you chose in part (a) and the final exam is higher?

If Exam 2 is later in the course, perhaps a student's performance is more established and their score for a later exam is more likely to mirror their achievement on the final.

8.6. Husbands and wives, Part I. The Great Britain Office of Population Census and Surveys once collected data on a random sample of 170 married couples in Britain, recording the age (in years) and heights (converted here to inches) of the husbands and wives.5 The scatterplot on the left shows the wife’s age plotted against her husband’s age, and the plot on the right shows wife’s height plotted against husband’s height.

(a) Describe the relationship between husbands’ and wives’ ages.

Strong, positive linear relationship.

(b) Describe the relationship between husbands’ and wives’ heights.

Very weak postive linear relationship.

(c) Which plot shows a stronger correlation? Explain your reasoning.

Ages. Less variance of residuals around a fitted line.

(d) Data on heights were originally collected in centimeters, and then converted to inches. Does this con-
version affect the correlation between husbands’ and wives’ heights?

No.

8.7. Match the correlation, Part I. Match each correlation to the corresponding scatterplot.

(a) R = −0.7. 4.
(b) R = 0.45. 3.
(c) R = 0.06. 1.
(d) R = 0.92. 2.

8.8. Match the correlation, Part I. Match each correlation to the corresponding scatterplot.

(a) R = 0.49. 2.
(b) R = −0.48. 4.
(c) R = −0.03. 3. 
(d) R = −0.85. 1. 

8.9. Speed and height. 1,302 UCLA students were asked to fill out a survey where they were asked about their height, fastest speed they have ever driven, and gender. The scatterplot on the left displays the relationship between height and fastest speed, and the scatterplot on the right displays the breakdown by gender in this relationship.

(a) Describe the relationship between height and fastest speed.

Medium, positive linear relationship. 

(b) Why do you think these variables are positively associated?

There is a confounding variable.

(c) What role does gender play in the relationship between height and fastest driving speed?

Males want to drive faster. They are also taller.

8.10. Guess the correlation. Eduardo and Rosie are both collecting data on number of rainy days in a year and the total rainfall for the year. Eduardo records rainfall in inches and Rosie in centimeters. How will their correlation coefficients compare?

Their coefficients should be the same. Slopes should be the same irrespective of axis scale.

8.11. The Coast Starlight, Part I. The Coast Starlight Amtrak train runs from Seattle to Los Angeles. The scatterplot below displays the distance between each stop (in miles) and the amount of time it takes to travel from one stop to another (in minutes).
(a) Describe the relationship between distance and travel time.

A weak, positive linear relationship. I should have mentioned the clustering in the lower left.

(b) How would the relationship change if travel time was instead measured in hours, and distance was instead measured in kilometers?

None.

(c) Correlation between travel time (in
miles) and distance (in minutes) is
r = 0.636. What is the correlation
between travel time (in kilometers) and distance (in hours)?

That doesn't make sense. The units for time and distance are paired with the wrong measures.

8.12. Crawling babies, Part I. A study conducted at the University of Denver investigated whether babies take longer to learn to crawl in cold months, when they are often bundled in clothes that restrict their movement, than in warmer months.6 Infants born during the study year were split into twelve groups, one for each birth month. We consider the average crawling age of babies in each group against the average tem- perature when the babies are six months old (that’s when babies often begin trying to crawl). Temperature is measured in degrees Fahrenheit (◦F) and age is measured in weeks.
(a) Describe the relationship between temperature and crawling age.

Weak, negative linear relationship.

(b) How would the relationship change if
temperature was measured in degrees
Celsius (◦C) and age was measured in
months?

None.

(c) The correlation between temperature
in ◦F and age in weeks was r = −0.70.
If we converted the temperature to ◦C
and age to months, what would the correlation be?

The same, -0.70.

8.13. Body measurements, Part I. Researchers studying anthropometry collected body girth measurements and skeletal diameter measurements, as well as age, weight, height and gender for 507 physically active individuals.7 The scatterplot below shows the relationship between height and shoulder girth (over deltoid muscles), both measured in centimeters.
(a) Describe the relationship between shoulder girth and height.

Medium, positive linear relationship.

(b) How would the relationship change if shoulder girth was measured in inches while the units of height remained in centimeters?

None.

8.14. Body measurements, Part II. The scatterplot below shows the relationship between weight measured in kilograms and hip girth measured in centimeters from the data described in Exercise 8.13.
(a) Describe the relationship between hip girth and weight.

This doesn't look linear. There are two tracks. I think there is a confounding variable, namely sex.

(b) How would the relationship change if weight was measured in pounds while the units for hip girth remained in centimeters?

None.

8.15. Correlation, Part I. What would be the correlation between the ages of husbands and wives if men always married woman who were
(a) 3 years younger than themselves?

1.0.

(b) 2 years older than themselves?

1.0.

(c) half as old as themselves?

0.5. I think the book's answer (1.0), is mistaken.

8.16. Correlation, Part II. What would be the correlation between the annual salaries of males and females at a company if for a certain type of position men always made
(a) $5,000 more than women?

$sal_m$ = $sal_w$ + 5000

(b) 25% more than women?

$sal_m$ = 1.25 * $sal_w$

(c) 15% less than women?

$sal_m$ = 0.85 * $sal_w$
