---
title: "OpenIntro Statistics"
subtitle: "Chapter 5 Exercises"
author: "Jai Jeffryes"
date: "4/29/2020 - 5/11/2020"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# https://stackoverflow.com/questions/5352099/how-to-disable-scientific-notation
# https://stackoverflow.com/questions/25946047/how-to-prevent-scientific-notation-in-r
options(scipen = 999)
```

## Notes

### Small sample hypothesis testing for a proportion
Online supplement.

- [Clopper-Pearson interval](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval)

## Ex. 6.1
Vegetarian college students. Suppose that 8\% 
of college students are vegetarians. Determine if the following statements are 
true or false, and explain your reasoning.

- The distribution of the sample proportions of vegetarians in random 
samples of size 60 is approximately normal since $n \ge 30$.
  - False. The first condition fails. $0.08 * 30 =$ `r 0.08 * 30` 
- The distribution of the sample proportions of vegetarian college 
students in random samples of size 50 is right skewed.
  - True. Due to CLT, when $np < 10$, there is skew, and the proportion is less than 0.5, in which case the skew is to the right.
- A random sample of 125 college students where 12\% are vegetarians 
would be considered unusual.
  - True. The Z-score for 12\% is: `r (0.12 - 0.08) / sqrt((0.08 * (1 - 0.08)) / 125)` That distance is right at the boundary for 95\% of expected observations if the proportion of vegetarians is 8\%. **ANSWER: False. The book considers this frequency not unusual.
- A random sample of 250 college students where 12\% are vegetarians 
would be considered unusual.
  - Even more true. Increasing the samples reduces the error. Now The Z-score for 12\% is: `r (0.12 - 0.08) / sqrt((0.08 * (1 - 0.08)) / 250)` That distance is the boundary for 99\% of expected observations if the proportion of vegetarians is 8\%.
- The standard error would be reduced by one-half if we increased the 
sample size from 125 to 250.
  - False. The reduction is by the root of 2.

## Ex. 6.2
Young Americans, Part I. About 77\% of 
young adults think they can achieve the American dream. Determine if the 
following statements are true or false, and explain your reasoning.

- The distribution of sample proportions of young Americans who think 
they can achieve the American dream in samples of size 20 is left skewed.
  - True. Conditions fail and the proportion is greater than 0.5, so left skewed.
- The distribution of sample proportions of young Americans who think 
they can achieve the American dream in random samples of size 40 is 
approximately normal since $n \ge 30$.
  - False. The number of failures expected in that sample still amounts to less than 10.
- A random sample of 60 young Americans where 85\% think they can achieve 
the American dream would be considered unusual.
  False. Z-score: `r (0.85 - 0.77) / sqrt((0.77 * (1 - 0.77)) / 60)`
- A random sample of 120 young Americans where 85\% think they can 
achieve the American dream would be considered unusual.
  - True. Z-score: `r (0.85 - 0.77) / sqrt((0.77 * (1 - 0.77)) / 120)`
  
## Ex. 6.3
Orange tabbies. Suppose that 90\% of orange
tabby cats are male. Determine if the following statements are true or false, 
and explain your reasoning.

-  The distribution of sample proportions of random samples of size 30 is 
left skewed.
-  Using a sample size that is 4 times as large will reduce the standard 
error of the sample proportion by one-half.
-  The distribution of sample proportions of random samples of size 140 is 
approximately normal.
-  The distribution of sample proportions of random samples of size 280 is 
approximately normal.

## Ex. 6.4
Young Americans, Part II. About 25\% of 
young Americans have delayed starting a family due to the continued economic 
slump. Determine if the following statements are true or false, and explain 
your reasoning.

-  The distribution of sample proportions of young Americans who have 
delayed starting a family due to the continued economic slump in random 
samples of size 12 is right skewed.
-  In order for the distribution of sample proportions of young Americans 
who have delayed starting a family due to the continued economic slump to be 
approximately normal, we need random samples where the sample size is at 
least 40.
-  A random sample of 50 young Americans where 20\% have delayed starting 
a family due to the continued economic slump would be considered unusual.
-  A random sample of 150 young Americans where 20\% have delayed 
starting a family due to the continued economic slump would be considered 
unusual.
-  Tripling the sample size will reduce the standard error of the sample 
proportion by one-third.

## Ex. 6.5
Gender equality.
The General Social Survey asked a random sample of
1,390 Americans the following question:
"On the whole, do you think it should or should not be
the government's responsibility to  promote equality
between men and women?''
82\% of the respondents said it "should be''.
At a 95\% confidence level, this sample has 2\% margin of error.
Based on this information, determine if the following statements
are true or false, and explain your reasoning.

-  We are 95\% confident that between 80\% and 84\% of Americans in this 
sample think it's the government's responsibility to promote equality between 
men and women.
-  We are 95\% confident that between 80\% and 84\% of all Americans 
think it's the government's responsibility to promote equality between 
men and women.
-  If we considered many random samples of 1,390 Americans, and we calculated 
95\% confidence intervals for each, 95\% of these intervals would include the 
true population proportion of Americans who think it's the government's 
responsibility to promote equality between men and women.
-  In order to decrease the margin of error to 1\%, we would need to 
quadruple (multiply by 4) the sample size.
-  Based on this confidence interval, there is sufficient evidence to 
conclude that a majority of Americans think it's the government's responsibility 
to promote equality between men and women.

% n = 1390
% should be: 1142
% p = 1142/1390 = 0.82
% me = sqrt(.82*.08/1390)*1.96 = 0.02

## Ex. 6.6
Elderly drivers. 
The Marist Poll published a report stating that 66\% of adults nationally 
think licensed drivers should be required to retake their road test once 
they reach 65 years of age. It was also reported that interviews were 
conducted on 1,018 American adults, and that the margin of error was 3\% 
using a 95\% confidence level.

-  Verify the margin of error reported by The Marist Poll. 
-  Based on a 95\% confidence interval, does the poll provide convincing 
evidence that \textit{more than} 70\% of the population think that licensed 
drivers should be required to retake their road test once they turn 65?

## Ex. 6.7
Fireworks on July 4$^{\text{th}}$. A local 
news outlet reported that 56\% of 600 randomly sampled Kansas residents planned 
to set off fireworks on July $4^{th}$. Determine the margin of error for the 
56\% point estimate using a 95\% confidence level.

## Ex. 6.8
Life rating in Greece. Greece has faced a 
severe economic crisis since the end of 2009. A Gallup poll surveyed 1,000 
randomly sampled Greeks in 2011 and found that 25\% of them said they would 
rate their lives poorly enough to be considered "suffering''.

-  Describe the population parameter of interest. What is the value of the 
point estimate of this parameter?
-  Check if the conditions required for constructing a confidence interval 
based on these data are met.
-  Construct a 95\% confidence interval for the proportion of Greeks who 
are "suffering".
-  Without doing any calculations, describe what would happen to the 
confidence interval if we decided to use a higher confidence level.
-  Without doing any calculations, describe what would happen to the 
confidence interval if we used a larger sample.

## Ex. 6.9
Study abroad.
A survey on 1,509 high school seniors who took the SAT
and who completed an optional web survey shows that
55\% of high school seniors are fairly certain that
they will participate in a study abroad program in 
college.

- 
    Is this sample a representative sample from the population
    of all high school seniors in the US?
    Explain your reasoning.
- 
    Let's suppose the conditions for inference are met.
    Even if your answer to part (a) indicated that this approach
    would not be reliable, this analysis may still be interesting
    to carry out (though not report).
    Construct a 90\% confidence interval for the proportion of high
    school seniors (of those who took the SAT) who are fairly certain
    they will participate in a study abroad program in college,
    and interpret this interval in context.
- 
    What does "90\% confidence" mean?
- 
    Based on this interval, would it be appropriate to claim that
    the majority of high school seniors are fairly certain that they
    will participate in a study abroad program in college?

## Ex. 6.10
Legalization of marijuana, Part I. 
The General Social Survey asked 1,578 US residents:
"Do you think the use of marijuana should be made legal, or not?''
61\% of the respondents said 
it should be made legal.

-  Is 61\% a sample statistic or a population parameter? Explain.
-  Construct a 95\% confidence interval for the proportion of US 
residents who think marijuana should be made legal, and interpret it in the 
context of the data.
-  A critic points out that this 95\% confidence interval is only 
accurate if the statistic follows a normal distribution, or if the normal 
model is a good approximation. Is this true for these data? Explain.
-  A news piece on this survey's findings states, "Majority of Americans 
think marijuana should be legalized.'' Based on your confidence 
interval, is this news piece's statement justified? 

% 2348 surveyed
% 770 not asked question
% 2348 - 770 = 1578 asked question
% 968 said legalize
% 968 / 1578 = 0.61

## Ex. 6.11
National Health Plan, Part I.
A \textit{Kaiser Family Foundation} poll for US adults
in 2019 found that 79\% of Democrats, 55\% of Independents,
and 24\% of Republicans supported a generic "National Health Plan''.
There were 347 Democrats, 298 Republicans, and 617 Independents
surveyed.

- 
    A political pundit on TV claims that a majority of Independents
    support a National Health Plan.
    Do these data provide strong evidence to support this type
    of statement?
- 
    Would you expect a confidence interval for the proportion
    of Independents who oppose the public option plan to
    include 0.5?
    Explain.

## Ex. 6.12
Is college worth it? Part I. Among a simple 
random sample of 331 American adults who do not have a four-year college degree 
and are not currently enrolled in school, 48\% said they decided not to go to 
college because they could not afford school.

-  A newspaper article states that only a minority of the Americans who 
decide not to go to college do so because they cannot afford it and uses the 
point estimate from this survey as evidence. Conduct a hypothesis test to 
determine if these data provide strong evidence supporting this statement.
-  Would you expect a confidence interval for the proportion of American 
adults who decide not to go to college because they cannot afford it to 
include 0.5? Explain.

## Ex. 6.13
Taste test.
Some people claim that they can tell the 
difference between a diet soda and a regular soda
in the first sip.
A researcher wanting to test this claim randomly sampled 80 such people.
He then filled 80 
plain white cups with soda, half diet and half regular
through random assignment, 
and asked each person to take one sip from their cup
and identify the soda as 
diet or regular.
53 participants correctly identified the soda.

-  Do these data provide strong evidence that these
  people are any better or worse than random guessing at
  telling the difference between diet and regular soda?
-  Interpret the p-value in this context.

## Ex. 6.14
Is college worth it? Part II. 
Exercise 6.12 presents the results of a poll where 
48\% of 331 Americans who decide to not go to college do so because they 
cannot afford it.

-  Calculate a 90\% confidence interval for the proportion of Americans 
who decide to not go to college because they cannot afford it, and interpret 
the interval in context.
-  Suppose we wanted the margin of error for the 90\% confidence level to 
be about 1.5\%. How large of a survey would you recommend?

## Ex. 6.15
National Health Plan,
    Part II. 
Exercise 6.11 presents the results
of a poll evaluating support for a generic
"National Health Plan'' in the US in 2019,
reporting that 55\% of Independents are supportive.
If we wanted to estimate this number to within 1\% with
90\% confidence, what would be an appropriate sample size?

## Ex. 6.16
Legalize Marijuana, Part II. As 
discussed in Exercise 6.10,
the General Social Survey reported a sample where about
61\% of US residents thought marijuana should be made legal.
If we wanted to limit the margin of error of 
a 95\% confidence interval to 2\%, about how many
Americans would we need to survey?

## Ex. 6.17
Social experiment, Part I. A "social 
experiment" conducted by a TV program questioned what people do when they see 
a very obviously bruised woman getting picked on by her boyfriend. On two 
different occasions at the same restaurant, the same couple was depicted. In 
one scenario the woman was dressed "provocatively'' and in the other 
scenario the woman was dressed "conservatively''. The table below shows how 
many restaurant diners were present under each scenario, and whether or not 
they intervened.

Explain why the sampling distribution of the difference between the 
proportions of interventions under provocative and conservative scenarios 
does not follow an approximately normal distribution.

## Ex. 6.18
Heart transplant success. The Stanford 
University Heart Transplant Study was conducted to determine whether an 
experimental heart transplant program increased lifespan. Each patient 
entering the program was officially designated a heart transplant candidate, 
meaning that he was gravely ill and might benefit from a new heart. Patients 
were randomly assigned into treatment and control groups. Patients in the 
treatment group received a transplant, and those in the control group did 
not. The table below displays how many patients survived and died in each 
group.
\begin{center}
\begin{tabular}{rcc}
\hline
            & control   & treatment \\ 
\hline
alive       & 4         & 24 \\ 
dead        & 30        & 45 \\ 
\hline
\end{tabular}
\end{center}
Suppose we are interested in estimating the difference in survival rate between 
the control and treatment groups using a confidence interval.
Explain why we cannot construct such an interval using the normal 
approximation. What might go wrong if we constructed the confidence interval 
despite this problem?

## Ex. 6.19
Gender and color preference. 
A study asked 1,924 male and 3,666 female undergraduate college students 
their favorite color.
A 95\% confidence interval for the difference between 
the proportions of males and females whose favorite color is black 
$(p_{male} - p_{female})$ was calculated to be (0.02, 0.06).
Based on this 
information, determine if the following statements are true or false, and 
explain your reasoning for each statement you identify as false.

-  We are 95\% confident that the true proportion of males whose favorite 
color is black is 2\% lower to 6\% higher than the true proportion of females 
whose favorite color is black.
-  We are 95\% confident that the true proportion of males whose favorite 
color is black is 2\% to 6\% higher than the true proportion of females whose 
favorite color is black.
-  95\% of random samples will produce 95\% confidence intervals that 
include the true difference between the population proportions of males and 
females whose favorite color is black.
-  We can conclude that there is a significant difference between the 
proportions of males and females whose favorite color is black and that the 
difference between the two sample proportions is too large to plausibly be 
due to chance.
-  The 95\% confidence interval for $(p_{female} - p_{male})$ cannot be 
calculated with only the information given in this exercise.

## Ex. 6.20
Government shutdown.
The United States federal government shutdown of 2018–2019 occurred
from December 22, 2018 until January 25, 2019, a span of 35 days.
A Survey USA poll of 614 randomly sampled Americans during this time
period reported that 48\% of those who make less than \$40,000 per
year and 55\% of those who make \$40,000 or more per year said the
government shutdown has not at all affected them personally.
A 95\% confidence interval for $(p_\text{$<$40K} - p_\text{$\ge$40K})$,
where $p$ is the proportion of those who said the government shutdown
has not at all affected them personally, is (-0.16, 0.02).
Based on this information, determine if the following statements are 
true or false, and explain your reasoning if you identify the statement
as false.

- 
    At the 5\% significance level, the data provide convincing
    evidence of a real difference in the proportion who are
    not affected personally between Americans who make less than
    \$40,000 annually and Americans who make \$40,000 annually.
- 
    We are 95\% confident that 16\% more to 2\% fewer Americans
    who make less than \$40,000 per year are not at all personally
    affected by the government shutdown compared to those who make
    \$40,000 or more per year.
- 
    A 90\% confidence interval for
    $(p_\text{$<$40K} - p_\text{$\ge$40K})$
    would be wider than the $(-0.16, 0.02)$ interval.
- 
    A 95\% confidence interval for
    $(p_\text{$\ge$40K} - p_\text{$<$40K})$
    is (-0.02, 0.16).

% p1 = 0.48
% p2 = 0.55
% n1 = 162
% n2 = 452
% ((p1 - p2) + c(-1,1) * 1.96 * sqrt( (p1*(1-p1)/n1) + (p2*(1-p2)/n2)) ) %>% round(2)
% (-0.16, 0.02)

## Ex. 6.21
National Health Plan,
    Part III.
Exercise 6.11
presents the results of a poll evaluating support for
a generically branded "National Health Plan''
in the United States.
79\% of 347 Democrats and 55\% of 617 Independents
support a National Health Plan.

- 
    Calculate a 95\% confidence interval for the
    difference between the proportion of Democrats
    and Independents who support a National
    Health Plan $(p_{D} - p_{I})$, and interpret
    it in this context.
    We have already checked conditions for you.
- 
    True or false:
    If we had picked a random Democrat and a random
    Independent at the time of this poll, it is more
    likely that the Democrat would support the National
    Health Plan than the Independent.

## Ex. 6.22
Sleep deprivation, CA vs. OR, Part I. According to 
a report on sleep deprivation by the Centers for Disease Control and Prevention, 
the proportion of California residents who reported insufficient rest or sleep 
during each of the preceding 30 days is 8.0\%, while this proportion is 8.8\% 
for Oregon residents. These data are based on simple random samples of 11,545 
California and 4,691 Oregon residents. Calculate a 95\% confidence interval 
for the difference between the proportions of Californians and Oregonians who 
are sleep deprived and interpret it in context of the data.

## Ex. 6.23
Offshore drilling, Part I.
A survey asked 827 randomly sampled registered voters in California
"Do you support? Or do you oppose? Drilling for oil and natural gas
off the Coast of California? Or do you not know enough to say?''
Below is the distribution of 
responses, separated based on whether or not the respondent graduated from 
college. 

\noindent\begin{minipage}[c]{0.6\textwidth}

-  What percent of college graduates and what percent of the non-college 
graduates in this sample do not know enough to have an opinion on drilling 
for oil and natural gas off the Coast of California?
-  Conduct a hypothesis test to determine if the data provide strong 
evidence that the proportion of college graduates who do not have an opinion 
on this issue is different than that of non-college graduates.

\end{minipage}
\begin{minipage}[c]{0.4\textwidth}
\begin{center}
\begin{tabular}{l c c}
			& \multicolumn{2}{c}{\textit{College Grad}} \\
\cline{2-3}
			& Yes		& No	\\
\cline{1-3}
Support		& 154		& 132	\\
Oppose		& 180		& 126	\\
Do not know	& 104		& 131	\\
\cline{1-3}
 Total		& 438		& 389		
\end{tabular}
\end{center}
\end{minipage}

## Ex. 6.24
Sleep deprivation, CA vs. OR, Part II. 
Exercise 6.22 provides data on sleep deprivation rates of 
Californians and Oregonians. The proportion of California residents who 
reported insufficient rest or sleep during each of the preceding 30 days is 
8.0\%, while this proportion is 8.8\% for Oregon residents. These data are 
based on simple random samples of 11,545 California and 4,691 Oregon 
residents. 

-  Conduct a hypothesis test to determine if these data provide strong 
evidence the rate of sleep deprivation is different for the two states. 
(Reminder: Check conditions)
-  It is possible the conclusion of the test in part (a) is incorrect. If 
this is the case, what type of error was made?

## Ex. 6.25
Offshore drilling, Part II.
Results of a poll evaluating support for drilling for oil
and natural gas off the coast of California were introduced
in Exercise 6.23.
\begin{center}
\begin{tabular}{l c c}
				& \multicolumn{2}{c}{\textit{College Grad}} \\
\cline{2-3}
						& Yes		& No				\\
\cline{1-3}
Support		& 154		& 132			\\
Oppose		& 180		& 126			\\
Do not know	& 104		& 131			\\
\cline{1-3}
 Total		& 438		& 389		
\end{tabular}
\end{center}

-  What percent of college graduates and what percent of the non-college 
graduates in this sample support drilling for oil and natural gas off the Coast 
of California?
-  Conduct a hypothesis test to determine if the data provide strong evidence 
that the proportion of college graduates who support off-shore drilling in California 
is different than that of non-college graduates.

## Ex. 6.26
Full body scan, Part I. A news article 
reports that "Americans have differing views on two potentially inconvenient 
and invasive practices that airports could implement to uncover potential 
terrorist attacks." This news piece was based on a survey conducted among a 
random sample of 1,137 adults nationwide, where one of the questions on the 
survey was "Some airports are 
now using `full-body' digital x-ray machines to electronically screen 
passengers in airport security lines. Do you think these new x-ray machines 
should or should not be used at airports?" Below is a summary of responses 
based on party affiliation.

-  Conduct an appropriate hypothesis test evaluating whether there is a 
difference in the proportion of Republicans and Democrats who think the full-
body scans should be applied in airports. Assume that all relevant conditions 
are met.
-  The conclusion of the test in part (a) may be incorrect, meaning a 
testing error was made. If an error was made, was it a Type 1 or a Type 2 
Error? Explain.

## Ex. 6.27
Sleep deprived transportation workers. 
The National Sleep Foundation conducted a survey on the sleep habits of 
randomly sampled transportation workers and a control sample of non-transportation 
workers. The results of the survey are shown below.

Conduct a hypothesis test to evaluate if these data provide evidence of a 
difference between the proportions of truck drivers and non-transportation 
workers (the control group) who get less than 6 hours of sleep per day, i.e. 
are considered sleep deprived.

## Ex. 6.28
Prenatal vitamins and Autism. 
Researchers studying the link between prenatal vitamin use and autism 
surveyed the mothers of a random sample of children aged 24 - 60 months with 
autism and conducted another separate random sample for children with typical 
development. The table below shows the number of mothers in each group who 
did and did not use prenatal vitamins during the three months before 
pregnancy (periconceptional period).

-  State appropriate hypotheses to test for independence of use of 
prenatal vitamins during the three months before pregnancy and autism.
-  Complete the hypothesis test and state an appropriate conclusion. 
(Reminder: Verify any necessary conditions for the test.)
-  A New York Times article reporting on this study was titled "Prenatal 
Vitamins May Ward Off Autism". Do you find the title of this article to be 
appropriate? Explain your answer. Additionally, propose an alternative title.

## Ex. 6.29
HIV in sub-Saharan Africa.
In July 2008 the US National Institutes of Health announced
that it was stopping a clinical study early because of unexpected
results.
The study population consisted of HIV-infected women in sub-Saharan
Africa who had been given single dose Nevaripine (a treatment for HIV)
while giving birth, to prevent transmission of HIV to the infant.
The study was a randomized comparison of continued
treatment of a woman (after successful childbirth)
with Nevaripine vs Lopinavir, a second drug used to treat HIV.
240 women participated in the study;
120 were randomized to each of the two treatments.
Twenty-four weeks after starting the study treatment,
each woman was tested to determine if the HIV infection
was becoming worse (an outcome called \textit{virologic failure}).
Twenty-six of the 120 women treated with Nevaripine experienced
virologic failure, while 10 of the 120 women treated with the
other drug experienced virologic failure.

-  Create a two-way table presenting the results of this study.
-  State appropriate hypotheses to test for difference in virologic failure
rates between treatment groups.
-  Complete the hypothesis test and state an appropriate conclusion. 
(Reminder: Verify any necessary conditions for the test.)

## Ex. 6.30
An apple a day keeps the doctor
    away.
A physical education teacher at a high school wanting
to increase awareness on issues of nutrition and health
asked her students at the beginning of the semester
whether they believed the expression
"an apple a day keeps the doctor away'',
and 40\% of the students responded yes.
Throughout the semester she started each class with
a brief discussion of a study highlighting positive
effects of eating more fruits and vegetables.
She conducted the same apple-a-day survey at the end
of the semester, and this time 60\% of the students
responded yes.
Can she used a two-proportion method from this section
for this analysis?
Explain your reasoning.

## Ex. 6.31
True or false, Part I. Determine if the statements below 
are true or false. For each false statement, suggest an alternative wording to 
make it a true statement.

-  The chi-square distribution, just like the normal distribution, has two 
parameters, mean and standard deviation.
-  The chi-square distribution is always right skewed, regardless of the 
value of the degrees of freedom parameter.
-  The chi-square statistic is always positive.
-  As the degrees of freedom increases, the shape of the chi-square 
distribution becomes more skewed.

## Ex. 6.32
True or false, Part II. Determine if the statements below 
are true or false. For each false statement, suggest an alternative wording to 
make it a true statement.

-  As the degrees of freedom increases, the mean of the chi-square 
distribution increases.
-  If you found $\chi^2 = 10$ with $df = 5$ you would fail to reject $H_0$ 
at the 5\% significance level.
-  When finding the p-value of a chi-square test, we always shade the tail 
areas in both tails.
-  As the degrees of freedom increases, the variability of the chi-square 
distribution decreases.

## Ex. 6.33
Open source textbook. A professor using 
an open source introductory statistics book predicts that 60\% of the 
students will purchase a hard copy of the book, 25\% will print it out from 
the web, and 15\% will read it online. At the end of the semester he asks his 
students to complete a survey where they indicate what format of the book 
they used. Of the 126 students, 71 said they bought a hard copy of the book, 
30 said they printed it out from the web, and 25 said they read it online.

-  State the hypotheses for testing if the professor's predictions were 
inaccurate.
-  How many students did the professor expect to buy the book, print the 
book, and read the book exclusively online?
-  This is an appropriate setting for a chi-square test. List the 
conditions required for a test and verify they are satisfied.
-  Calculate the chi-squared statistic, the degrees of freedom associated 
with it, and the p-value.
-  Based on the p-value calculated in part (d), what is the conclusion of 
the hypothesis test? Interpret your conclusion in this context.

## Ex. 6.34
Barking deer.
Microhabitat factors associated with forage and bed sites
of barking deer in Hainan Island, China were examined.
In this region woods make up 4.8\% of the land,
cultivated grass plot makes up 14.7\%, and deciduous forests
make up 39.6\%.
Of the 426 sites where the deer forage, 4 were categorized
as woods, 16 as cultivated grassplot, and 61 as deciduous forests.
The table below summarizes these data.

-  Write the hypotheses for testing if barking deer prefer to forage in 
certain habitats over others.
-  What type of test can we use to answer this research question?
-  Check if the assumptions and conditions required for this test are 
satisfied.
-  Do these data provide convincing evidence that barking deer prefer to 
forage in certain habitats over others? Conduct an appropriate hypothesis 
test to answer this research question.

## Ex. 6.35
Quitters. Does being part of a 
support group affect the ability of people to quit smoking? A county 
health department enrolled 300 smokers in a randomized experiment. 150 
participants were assigned to a group that used a nicotine patch and 
met weekly with a support group; the other 150 received the patch and 
did not meet with a support group. At the end of the study, 40 of the 
participants in the patch plus support group had quit smoking while 
only 30 smokers had  quit in the other group.

-  Create a two-way table presenting the results of this study.
-  Answer each of the following questions under the null hypothesis 
that being part of a support group does not affect the ability of 
people to quit smoking, and indicate whether the expected values are 
higher or lower than the observed values.

-  How many subjects in the "patch + support" group would you 
expect to quit?
-  How many subjects in the "patch only" group would you expect to 
not quit?

## Ex. 6.36
Full body scan, Part II. The 
table below summarizes a data set we first encountered in 
Exercise 6.26 regarding views on full-body 
scans and political affiliation. The differences in each political 
group may be due to chance. Complete the following computations under 
the null hypothesis of independence between an individual's party 
affiliation and his support of full-body scans. It may be useful to 
first add on an extra column for row totals before proceeding with the 
computations.

-  How many Republicans would you expect to not support the use of 
full-body scans?
-  How many Democrats would you expect to support the use of full-
body scans?
-  How many Independents would you expect to not know or not answer?

## Ex. 6.37
Offshore drilling, Part III. 
The table below summarizes a data set we first encountered in 
Exercise 6.23 that examines the 
responses of a random sample of college graduates and non-graduates on 
the topic of oil drilling. Complete a chi-square test for these data to 
check whether there is a statistically significant difference in 
responses from college graduates and non-graduates.

## Ex. 6.38
Parasitic worm.
Lymphatic filariasis is a disease caused by a parasitic worm.
Complications of the disease can lead to extreme swelling
and other complications.
Here we consider results from a randomized experiment
that compared three
different drug treatment options to clear people of the
this parasite, which people are working to eliminate entirely.
The results for the second year of the study are
given below:

- 
    Set up hypotheses for evaluating
    whether there is any difference in the
    performance of the treatments,
    and also check conditions.
- 
    Statistical software was used to run
    a chi-square test, which output:
  
    Use these results to evaluate the hypotheses
    from part (a),
    and provide a conclusion
    in the context of the problem.

## Ex. 6.39
Active learning. A teacher wanting to 
increase the active learning component of her course is concerned about 
student reactions to changes she is planning to make. She conducts a survey 
in her class, asking students whether they believe more active learning in 
the classroom (hands on exercises) instead of traditional lecture will helps 
improve their learning. She does this at the beginning and end of the 
semester and wants to evaluate whether students' opinions have changed over 
the semester. Can she used the methods we learned in this chapter for this 
analysis? Explain your reasoning.

## Ex. 6.40
Website experiment.
The OpenIntro website occasionally experiments with design
and link placement.
We conducted one experiment testing three different placements
of a download link for this textbook on the book's main page
to see which location, if any, led to the most downloads.
The number of site visitors included in the experiment
was 701 and is captured in one of the response combinations
in the following table:

- 
    Calculate the actual number of site visitors in each
    of the six response categories.
- 
    Each individual in the experiment had an equal chance of
    being in any of the three experiment groups.
    However, we see that there are slightly different
    totals for the groups.
    Is there any evidence that the groups were actually imbalanced?
    Make sure to clearly state hypotheses, check conditions,
    calculate the appropriate test statistic and the p-value,
    and make your conclusion in context of the data.
- 
   Complete an appropriate hypothesis test to check whether
   there is evidence that there is a higher rate of site visitors
   clicking on the textbook link in any of the three groups.

## Ex. 6.41
Shipping holiday gifts. A 
local news survey asked 500 randomly sampled Los Angeles residents 
which shipping carrier they prefer to use for shipping holiday gifts. 
The table below shows the distribution of responses by age group as 
well as the expected counts for each cell (shown in parentheses).

-  State the null and alternative hypotheses for testing for independence 
of age and preferred shipping method for holiday gifts among Los Angeles residents.
-  Are the conditions for inference using a chi-square test satisfied?

## Ex. 6.42
The Civil War.
A national survey conducted 
among a simple random sample of 1,507 adults shows that 56\% of
Americans think the Civil War is still relevant to American politics and 
political life.

-  Conduct a hypothesis test to determine if these data provide strong 
evidence that the majority of the Americans think the Civil War is still 
relevant.
-  Interpret the p-value in this context.
-  Calculate a 90\% confidence interval for the proportion of Americans 
who think the Civil War is still relevant. Interpret the interval in this 
context, and comment on whether or not the confidence interval agrees with 
the conclusion of the hypothesis test.

## Ex. 6.43
College smokers. We are interested 
in estimating the proportion of students at a university who smoke. Out of a 
random sample of 200 students from this university, 40 students smoke.

-  Calculate a 95\% confidence interval for the proportion of students at 
this university who smoke, and interpret this interval in context. 
(Reminder: Check conditions.)
-  If we wanted the margin of error to be no larger than 2\% at a 95\% 
confidence level for the proportion of students who smoke, how big of a 
sample would we need? 

## Ex. 6.44
Acetaminophen and liver damage. It 
is believed that large doses of acetaminophen (the active ingredient in over 
the counter pain relievers like Tylenol) may cause damage to the liver. A 
researcher wants to conduct a study to estimate the proportion of 
acetaminophen users who have liver damage. For participating in this study, 
he will pay each subject \$20 and provide a free medical consultation if the 
patient has liver damage.

-  If he wants to limit the margin of error of his 98\% confidence 
interval to 2\%, what is the minimum amount of money he needs to set aside 
to pay his subjects?
-  The amount you calculated in part (a) is substantially over his budget 
so he decides to use fewer subjects. How will this affect the width of his 
confidence interval?

## Ex. 6.45
Life after college. We are interested in 
estimating the proportion of graduates at a mid-sized university who found 
a job within one year of completing their undergraduate degree. Suppose we 
conduct a survey and find out that 348 of the 400 randomly sampled graduates 
found jobs. The graduating class under consideration included over 4500 students.

-  Describe the population parameter of interest. What is the value of 
the point estimate of this parameter?
-  Check if the conditions for constructing a confidence interval based 
on these data are met.
-  Calculate a 95\% confidence interval for the proportion of graduates 
who found a job within one year of completing their undergraduate degree at 
this university, and interpret it in the context of the data.
-  What does "95\% confidence" mean?
-  Now calculate a 99\% confidence interval for the same parameter and 
interpret it in the context of the data.
-  Compare the widths of the 95\% and 99\% confidence intervals. Which 
one is wider? Explain.

## Ex. 6.46
Diabetes and unemployment. A 
Gallup poll surveyed Americans about their employment status and whether or 
not they have diabetes. The survey results indicate that 1.5\% of the 47,774 
employed (full or part time) and 2.5\% of the 5,855 unemployed 18-29 year 
olds have diabetes.

-  Create a two-way table presenting the results of this study.
-  State appropriate hypotheses to test for difference in proportions of 
diabetes between employed and unemployed Americans.
-  The sample difference is about 1\%. If we completed the hypothesis 
test, we would find that the p-value is very small (about 0), meaning the 
difference is statistically significant. Use this result to explain the 
difference between statistically significant and practically significant 
findings.

## Ex. 6.47
Rock-paper-scissors. Rock-paper-scissors is a hand 
game played by two or more people where players choose to sign either rock, 
paper, or scissors with their hands. For your statistics class project, 
you want to evaluate whether players choose between these three options 
randomly, or if certain options are favored above others. You ask two friends 
to play rock-paper-scissors and count the times each option is played. The 
following table summarizes the data:

Use these data to evaluate whether players choose between these three options 
randomly, or if certain options are favored above others. Make sure to clearly 
outline each step of your analysis, and interpret your results in context of 
the data and the research question.

## Ex. 6.48
2010 Healthcare Law. On June 28, 2012 the 
U.S. Supreme Court upheld the much debated 2010 healthcare law, declaring it 
constitutional. A Gallup poll released the day after this decision indicates 
that 46\% of 1,012 Americans agree with this decision. At a 95\% confidence 
level, this sample has a 3\% margin of error. Based on this information, 
determine if the following statements are true or false, and explain your 
reasoning.

-  We are 95\% confident that between  43\% and 49\% of Americans in this 
sample support the decision of the U.S. Supreme Court on the 2010 healthcare 
law.
-  We are 95\% confident that between 43\% and 49\% of Americans support 
the decision of the U.S. Supreme Court on the 2010 healthcare law.
-  If we considered many random samples of 1,012 Americans, and we 
calculated the sample proportions of those who support the decision of the 
U.S. Supreme Court, 95\% of those sample proportions will be between 43\% and 
49\%.
-  The margin of error at a 90\% confidence level would be higher than 3\%.

## Ex. 6.49
Browsing on the mobile device. A 
survey of 2,254 American adults indicates that 17\% of cell phone owners
browse the internet exclusively on their phone rather than a computer
or other device.

-   According to an online article, a report from a mobile research 
company indicates that 38 percent of Chinese mobile web users only access 
the internet through their cell phones.
Conduct a hypothesis test to 
determine if these data provide strong evidence that the proportion of 
Americans who only use their cell phones to access the internet is different 
than the Chinese proportion of 38\%.
-  Interpret the p-value in this context.
-  Calculate a 95\% confidence interval for the proportion of Americans 
who access the internet on their cell phones, and interpret the interval in 
this context.

## Ex. 6.50
Coffee and Depression. 
Researchers conducted a study investigating the relationship between 
caffeinated coffee consumption and risk of depression in women. They 
collected data on 50,739 women free of depression symptoms at the start 
of the study in the year 1996, and these women were followed through 
2006. The researchers used questionnaires to collect data on 
caffeinated coffee consumption, asked each individual about physician-
diagnosed depression, and also asked about the use of antidepressants. 
The table below shows the distribution of incidences of depression by 
amount of caffeinated coffee consumption.

-  What type of test is appropriate for evaluating if there is an 
association between coffee intake and depression?
-  Write the hypotheses for the test you identified in part (a).
-  Calculate the overall proportion of women who do and do not 
suffer from depression.
-  Identify the expected count for the highlighted cell, and 
calculate the contribution of this cell to the test statistic, i.e. 
$(Observed-Expected)^2/Expected$.
-  The test statistic is $\chi^2=20.93$. What is the p-value?
-  What is the conclusion of the hypothesis test?
-  One of the authors of this study was quoted on the NYTimes as 
saying it was "too early to recommend that women load up on extra 
coffee" based on just this study.
Do you agree with this statement? Explain your reasoning.