---
title: "Data 605 - Assignment 14"
author: "Jai Jeffryes"
date: "5/10/2020"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#options(scipen = 999)
```

## Assignment
This week, we’ll work out some Taylor Series expansions of popular functions.

- $f(x) = \frac{1}{(1-x)}$
- $f(x) = e^x$
- $f(x) = ln(1 + x)$

For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion. Please submit your assignment as an R-Markdown document.

## Problem 1: $f(x) = \frac{1}{(1-x)}$
Am I just doing the Maclaurin Series version of this? The series is defined for $x = 0$. $x - 1$ is undefined because 0 would appear in the denominator.

Find the derivative of the function using the Chain Rule, letting $u = 1 - x$.
$$\frac{d}{dx} (\frac{1}{1-x}) = \frac{d}{dx} (1-x)^{-1} = (-1 \cdot (1 - x)^{-2}) \cdot(-1) = \frac{1}{(1 - x)^2}$$
Let's extend this to more derivatives and compute their value for $x = 0$.
$$f(x) =\frac{1}{(1-x)},\ f(0) = 1$$
$$f'(x) =\frac{1}{(1-x)^2},\ f'(0) = 1$$
$$f''(x) = \frac{2}{(1-x)^3},\ f''(0) = 2$$
$$f'''(x) =\frac{6}{(1-x)^4},\ f'''(0) = 6$$
$$f''''(x) =\frac{24}{(1-x)},\ f''''(0) = 24$$
$$f^{(n)}(x) = \frac{n!}{(1-x)^{(n + 1)}},\ f^{n}(0) = n!$$

### Answer
$$f(x) = \frac{1}{(1-x)} = \sum_{n = 1}^\infty \frac{n!}{(1-x)^{(n + 1)}}$$

## Problem 2: $f(x) = e^x$
Answering this problem proves that I watched David Jerison's video!

We'll center the Taylor expansion on $c = 0$
$$e^x = \sum_{n = 0}^\infty \frac{f^{(n)}(0)}{n!} x^n$$
Consider that the function $f(x) = e^x$ is its own derivative. Thus,
$$f(x) = e^x$$
$$f'(x) = e^x$$
$$f''(x) = e^x$$
$$Etc.$$

$$f^{(n)}(x) = e^x\bigg\rvert_{x = 0} = 1$$

Therefore, all the numerators in the expansion are 1.

### Answer
$$f(x) = e^x = \sum_{n = 0}^\infty \frac{1}{n!} x^n$$

This example computes the value of $e$ by setting $x = 1$
$$e = e^1 = 1 + 1 + \frac{1}{2!} + \frac{1}{3!} + \frac{1}{4!} + \dots$$

## Problem 3: $f(x) = ln(1 + x)$
Find the derivative of the function using the Chain Rule, letting $u = 1 + x$.
$$\frac{d}{dx} ln(1 + x) = \frac{1}{1 + x} \cdot 1 = \frac{1}{1 + x}$$

Successive derivatives alternate in polarity. We'll expand around $c = 0$.
$$f(x) = ln(1 + x),\ f(0) = 0$$
$$f'(x) = \frac{1}{1 + x},\ f'(0) = 1$$
$$f''(x) = \frac{-1}{(1 + x)^2},\ f''(0) = -1$$
$$f^{(3)}(x) = \frac{2}{(1 + x)^3},\ f^{(3)}(0) = 2$$
$$f^{(4)}(x) = \frac{-6}{(1 + x)^4},\ f^{(4)}(0) = -6$$
$$f^{(5)}(x) = \frac{24}{(1 + x)^5},\ f^{(5)}(0) = 24$$
$$f^{(n)}(x) = \sum_{n = 1}^{\infty} (-1)^{(n-1)}\frac{(n-1)!}{(1 + x)^n},\ f^{(n)}(0) = (-1)^{(n-1)}(n - 1)!$$

### Answer
$$f(x) = ln(1 + x) = \sum_{n = 1}^{\infty} (-1)^{(n-1)}\frac{(n-1)!}{(1 + x)^n}$$